package com.juebingliu.boot4enhance.domain.two;

import com.juebingliu.boot4enhance.common.enums.OrderStatus;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Id
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    private OrderStatus orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Id
     *
     * @return the value of order.Id
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Id
     *
     * @param id the value for order.Id
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    public OrderStatus getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbggenerated Wed Dec 12 15:43:00 CST 2018
     */
    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus;
    }

    @Override
    public String toString() {
        return "Order{" +
                "orderId= " + orderId + '\'' +
                ", orderStatus=" + orderStatus +
                '}';
    }
}